.TH "hub-cherry-pick" "1" "19 Jul 2019" "hub version 2.12.3" "hub manual"
.nh
.ad l
.SH "NAME"
hub\-cherry\-pick \- Cherry\-pick a commit from a fork on GitHub.
.SH "SYNOPSIS"
.P
\fB\fChub cherry\-pick\fR \fICOMMIT\-URL\fP
.br
\fB\fChub cherry\-pick\fR \fIUSER\fP@\fISHA\fP
.SH "SEE ALSO"
.P
hub\-am(1), hub(1), git\-cherry\-pick(1)

